on:
  push:
    branches: 
      - main
jobs:
  hello_world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello World
        run: echo Hello World
